name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug
        shell: pwsh
        run: |
          echo "GITHUB_WORKSPACE = $env:GITHUB_WORKSPACE"
          ls -Recurse

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Flake8
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          flake8 src tests

      - name: Run tests
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest --maxfail=1 --disable-warnings -q
