name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: pwsh
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with Flake8
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          pip install flake8
          flake8 src tests
      - name: Run tests
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q