name: Python-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Debug
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          echo "Installed packages:"
          python -m pip list

      - name: Run tests
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          python -m pytest --maxfail=1 --disable-warnings -q
