name: Python-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      PYTHONUTF8: 1
      PYTHONLEGACYWINDOWSSTDIO: utf-8

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4

    - name: Setup Python
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: '3.11'

    - name: Create and activate venv
      shell: pwsh
      run: |
        python -m venv .venv
        Set-ExecutionPolicy Bypass -Scope Process -Force
        .\.venv\Scripts\Activate.ps1

    - name: Install dependencies
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Add venv to PATH
      shell: pwsh
      run: |
        echo "$env:GITHUB_WORKSPACE\.venv\Scripts" >> $env:GITHUB_PATH

    - name: Run Linter
      run: flake8 src tests

    - name: Run Tests
      run: pytest --maxfail=1 --disable-warnings